apiVersion: v1
kind: Secret
metadata:
  name: tfgen-secret
  namespace: tfgen
  labels:
    app.kubernetes.io/name: tfgen
    app.kubernetes.io/part-of: tfgen
type: Opaque
data:
  POSTGRES_USER:     dGZnZW4=
  POSTGRES_PASSWORD: dGZnZW4xMjM=
  POSTGRES_DB:       dGVycmFmb3JtX2dlbmVyYXRvcg==
  DATABASE_URL: cG9zdGdyZXNxbDovL3RmZ2VuOnRmZ2VuMTIzQHRmZ2VuLXBvc3RncmVzLXN2Yzo1NDMyL3RlcnJhZm9ybV9nZW5lcmF0b3I=
  REDIS_URL: cmVkaXM6Ly90Zmdlbi1yZWRpcy1zdmM6NjM3OQ==
  JWT_SECRET: OWEwMmFiOGM0ODQyYzQ2MTM4YTNhNDc5ZWFiNzc4NjE1MGFhM2YwYTMwNGM4ZjA5ZmU0NjFkOWI3ODcxYTU0YQ==
  JWT_REFRESH_SECRET: OWEwMmFiOGM0ODQyYzQ2MTM4YTNhNDc5ZWFiNzc4NjE1MGFhM2YwYTMwNGM4ZjA5ZmU0NjFkOWI3ODcxYTU0YQ==
  ENCRYPT_KEY: MjgwODI4OWJkYjNlNGI4ZTZmMjliNWFmOTljOTEwNDhkNWU4ZGEzNjc1NzNhODJlZjRiZDJlNDljZWU1NzFjYQ==
  SMTP_USER: c3JpcmFqZW5kcmFwcmFzYWRkYWdndWJhdGlAZ21haWwuY29t
  SMTP_PASS: b2h1bCBzaXRrIHFhcHkgaG16bA==
  SMTP_FROM: VEZHZW4gPHRmZ2VuYWRtaW5AZ21haWwuY29tPg==
  FRONTEND_URL: aHR0cDovL3RmZ2VuLmV4YW1wbGUuY29t
